name: Manhunt_Plugin
version: 1.1.1
main: plugin.manhunt.manhunt_plugin.ManhuntPlugin
api-version: 1.17
commands:
  manhuntStart:
    description: Runs manhunt sim 9000
    usage: /manhuntStart name
  manhuntStop:
    description: Ends manhunt sim 9000