name: Manhunt_Plugin
version: 2.0.1
main: plugin.manhunt.manhunt_plugin.ManhuntPlugin
api-version: 1.17
commands:
  hunters:
    description: set hunters
    usage: /hunters [list of hunters]
  target:
    description: set hunted
    usage: /target [target]
  endhunt:
    description: Ends manhunt sim 9000
    usage: /endhunt