name: Manhunt_Plugin
version: 2.0.6
main: plugin.manhunt.manhunt_plugin.ManhuntPlugin
api-version: 1.18
commands:
  endgame:
    description: Ends manhunt sim 9000
    usage: /endgame
  newgame:
    description: creates new game
    usage: /newgame
  joingame:
    description: joins a game
    usage: /joingame