name: Manhunt_Plugin
version: 2.0.4
main: plugin.manhunt.manhunt_plugin.ManhuntPlugin
api-version: 1.18.1
commands:
  hunters:
    description: set hunters
    usage: /hunters [list of hunters]
  target:
    description: set hunted
    usage: /target [target]
  endgame:
    description: Ends manhunt sim 9000
    usage: /endgame
  listgames:
    description: Lists all active games
    usage: /listgames
